<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20190528213517 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription()
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE rfy_shop_domain_model_orderline DROP FOREIGN KEY FK_E94D5B67F5299398');
        $this->addSql('DROP INDEX IDX_E94D5B67F5299398 ON rfy_shop_domain_model_orderline');
        $this->addSql('ALTER TABLE rfy_shop_domain_model_orderline CHANGE `order` parent VARCHAR(40) DEFAULT NULL');
        $this->addSql('ALTER TABLE rfy_shop_domain_model_orderline ADD CONSTRAINT FK_E94D5B673D8E604F FOREIGN KEY (parent) REFERENCES rfy_shop_domain_model_order (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_E94D5B673D8E604F ON rfy_shop_domain_model_orderline (parent)');
    }

    /**
     * @param Schema $schema
     * @return void
     */
    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != 'mysql', 'Migration can only be executed safely on "mysql".');
        
        $this->addSql('ALTER TABLE rfy_shop_domain_model_orderline DROP FOREIGN KEY FK_E94D5B673D8E604F');
        $this->addSql('DROP INDEX IDX_E94D5B673D8E604F ON rfy_shop_domain_model_orderline');
        $this->addSql('ALTER TABLE rfy_shop_domain_model_orderline CHANGE parent `order` VARCHAR(40) DEFAULT NULL COLLATE utf8mb4_unicode_ci');
        $this->addSql('ALTER TABLE rfy_shop_domain_model_orderline ADD CONSTRAINT FK_E94D5B67F5299398 FOREIGN KEY (`order`) REFERENCES rfy_shop_domain_model_order (persistence_object_identifier)');
        $this->addSql('CREATE INDEX IDX_E94D5B67F5299398 ON rfy_shop_domain_model_orderline (`order`)');
    }
}